<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <BlockShotAssemblySuffix Condition="'$(BlockShotAssemblySuffix)' == ''">v0_1_13_dev</BlockShotAssemblySuffix>
    <AssemblyName>BlockShot.VintageStory.Core.$(BlockShotAssemblySuffix)</AssemblyName>
  </PropertyGroup>
</Project>
